my_data<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
my_subset<-subset(my_data,Date=="1/2/2007"|Date=="2/2/2007")
my_subset$Date <- as.Date(my_subset$Date, format="%d/%m/%Y")
my_subset$Time <- strptime(my_subset$Time, format="%H:%M:%S")
my_subset[1:1440,"Time"] <- format(my_subset[1:1440,"Time"],"2007-02-01 %H:%M:%S")
my_subset[1441:2880,"Time"] <- format(my_subset[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
png("Plot 4.png", height=480, width=480)
par(mfrow=c(2,2))
with(my_subset,{
  plot(my_subset$Time,as.numeric(as.character(my_subset$Global_active_power)),type="l",  xlab="",ylab="Global Active Power")  
  plot(my_subset$Time,as.numeric(as.character(my_subset$Voltage)), type="l",xlab="datetime",ylab="Voltage")
  plot(my_subset$Time,my_subset$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
  with(my_subset,lines(Time,as.numeric(as.character(Sub_metering_1))))
  with(my_subset,lines(Time,as.numeric(as.character(Sub_metering_2)),col="red"))
  with(my_subset,lines(Time,as.numeric(as.character(Sub_metering_3)),col="blue"))
  legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex = 0.6)
  plot(my_subset$Time,as.numeric(as.character(my_subset$Global_reactive_power)),type="l",xlab="datetime",ylab="Global_reactive_power")
})
dev.off()