my_data<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
my_subset<-subset(my_data,Date=="1/2/2007"|Date=="2/2/2007")
my_subset$Date <- as.Date(my_subset$Date, format="%d/%m/%Y")
my_subset$Time <- strptime(my_subset$Time, format="%H:%M:%S")
my_subset[1:1440,"Time"] <- format(my_subset[1:1440,"Time"],"2007-02-01 %H:%M:%S")
my_subset[1441:2880,"Time"] <- format(my_subset[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
png("Plot 2.png", height=480, width=480)
plot(my_subset$Time,as.numeric(as.character(my_subset$Global_active_power)),type="l",xlab="",ylab="Global Active Power (kilowatts)") 
title(main="Global Active my_data Vs Time")
dev.off()